spring:
  datasource:
    url: jdbc:postgresql://shoppingapp-db.cqtevsxag3ny.eu-central-1.rds.amazonaws.com:5432/shoppingappdb
    username: postgres
    password: 12345678

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: inventory-service

server:
  port: 0
  servlet:
    context-path: /api/inventory-service

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


